export const shopCategories = [
  { label: "Books & Stationery", value: "books" },
  { label: "Clothing & Apparel", value: "clothing" },
  { label: "Electronics & Gadgets", value: "electronics" },
  { label: "Home & Kitchen", value: "home-kitchen" },
  { label: "Beauty & Personal Care", value: "beauty" },
  { label: "Health & Wellness", value: "health" },
  { label: "Toys & Games", value: "toys" },
  { label: "Sports & Outdoors", value: "sports" },
  { label: "Groceries & Essentials", value: "groceries" },
  { label: "Jewelry & Accessories", value: "jewelry" },
  { label: "Automotive & Tools", value: "automotive" },
  { label: "Pet Supplies", value: "pets" },
  { label: "Art & Craft", value: "art-craft" },
  { label: "Furniture & Decor", value: "furniture" },
  { label: "Music & Instruments", value: "music" },
  { label: "Footwear", value: "footwear" },
  { label: "Baby Products", value: "baby" },
  { label: "Mobile & Accessories", value: "mobiles" },
  { label: "Gaming & Consoles", value: "gaming" },
  { label: "Garden & Outdoor", value: "garden" },
  { label: "Industrial & Scientific", value: "industrial" },
  { label: "Office Supplies", value: "office-supplies" },
  { label: "Watches & Wearables", value: "watches" },
  { label: "Travel & Luggage", value: "travel" },
  { label: "Lighting & Fixtures", value: "lighting" },
  { label: "Cleaning & Household", value: "cleaning" },
  { label: "Digital Products", value: "digital-products" },
  { label: "Software & Services", value: "software" },
  { label: "Religious & Spiritual", value: "spiritual" },
  { label: "Vintage & Collectibles", value: "vintage" },
  { label: "DIY & Tools", value: "diy" },
  { label: "Bedding & Linens", value: "bedding" },
  { label: "Eyewear & Optical", value: "eyewear" },
  { label: "Luxury Goods", value: "luxury" },
  { label: "Bags & Wallets", value: "bags" },
  { label: "Food & Beverages", value: "food" },
  { label: "Alcohol & Spirits", value: "alcohol" },
  { label: "Event Supplies", value: "events" },
  { label: "Party & Celebration", value: "party" },
  { label: "Wedding Essentials", value: "wedding" },
  { label: "Survival & Tactical", value: "survival" },
  { label: "Construction Supplies", value: "construction" },
  { label: "Medical Supplies", value: "medical" },
  { label: "Eco-Friendly Products", value: "eco-friendly" },
  { label: "Seasonal & Holiday", value: "seasonal" }
];
